### ISSUE TITLE
Question about Fmish in DoubleFusion

### ISSUE THREAD

**Issue by minh-nguyenhoang** [xavysp/TEED#9]
Hello and thank you for your amazing works. I'm new to edge detection field so I would like to ask you a question. When I inspect your code I find that the DoubleFusion layer, which output the final edge map of the network, ended with a Fmish activation layer. When I plot the function, it show that most part have near-zero or positive value (except a very a narrow range near zero which can output small negative values). And in the loss layer again tou put the output through a sigmoid so, basically what should be non-edge are now have values near 0.5, which doesn't make sense to me. Can you explain further about this choice?

**Comment by xavysp** [comment]
It's a great question. To be honest we did not detail this part in our preliminary  workshop paper. So we are preparing an extended and complete version to speak about the generalization ability of our TEED.

To give you a sneak peek, DoubleFusion help in the generalization capability using the supervised procedure with the aim of weak-supervision process because TEED is not designed to beat the dataset used for training but any downstream task of edge detection.
